services:
  pacman:
    build: .
    command: bash
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - pacman-env
        # - action: rebuild
        #   path: '**/*.py'
    networks:
      - app_network
    volumes:
      - pacman_volume:/data
    depends_on:
      rabbitmqserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 16g  # Increase this value
        reservations:
          devices:
            - capabilities: [gpu]
        
  rabbitmqserver:
    container_name: rabbitmqServer
    build:
      context: .
      dockerfile: ./rabbitMQ.Dockerfile
    hostname: "rabbitmq-host"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "pass"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    depends_on:
      rabbitmqserver:
        condition: service_healthy
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 3g  # Increase this value
        reservations:
          memory: 1g  # Ensure some memory is reserved
    mem_limit: 3g  # Set memory limit
    memswap_limit: 6g  # Set swap memory limit

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 8g  # Increase memory limit
          cpus: "2.0"  # Increase CPU allocation
        reservations:
          memory: 4g  # Ensure some memory is reserved
          cpus: "1.0"  # Reserve CPU resources

networks:
  app_network:

volumes:
  pacman_volume: